### PR TITLE
Add personal info

### PR DESCRIPTION
**Pull request by Cynicicm**
Related #6

## What is the purpose of the change

-   add wenjie's personal info

## Brief change log

-   Add name, educational background, interest and so on.

### CODE REVIEW

**Comment by leofang327** [comment]
Please add reviewers for this pull request, many thanks :)

**Comment by Cynicicm** [comment]
how can i add reviewers base on this version ?

**Comment by leofang327** [comment]
> how can i add reviewers base on this version ?

simply click the button after reviewers and choose the people, it doesn't matter that I have add myself to review this PR.

**Comment by Cynicicm** [comment]
> > how can i add reviewers base on this version ?
> 
> simply click the button after reviewers and choose the people, it doesn't matter that I have added myself to review this PR.

**Pull request merged**
